### ISSUE TITLE
Checklist in task description

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#1]
There is a difference how the checklist is shown in the description vs. the description editor.

Description:
![image](https://user-images.githubusercontent.com/6393629/228353416-2b8c77f9-5c5a-4e65-aa4c-45a5f363d8ab.png)

Editor:
![image](https://user-images.githubusercontent.com/6393629/228353483-fb4288b8-0ccb-400c-a633-4ecd2079e7d1.png)

**Comment by hrvojeerjavec** [comment]
I suppose the checklist in description should look the same as in the editor

**Comment by Lok3rs** [comment]
@hrvojeerjavec 

Hello ;-)

We didn't make it looking exactly as in Markdown Editor, but now you can see proper checkboxes instead of [ x ]. You can see that already in app

Thanks for all issues/ideas :-)
