### ISSUE TITLE
Number of boats in the list per screen

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#10]
Is it possible to compress the list so more boats are visible in the list. For example the name of the client is not as important to be visible in the list. We can find it through search if needed. We have 32/33 boats per base, and it would improve the overview a lot.

**Comment by yergom** [comment]
@hrvojeerjavec could you be a bit more specific? What list are you referring? My guess is that you are talking about the booking list in the mobile app. If that's the case, it might make sense to have an option to decide whether we want to show full details or a compressed version, with only the booking and the states? How much information would you like to see in such a view?

I'm also wondering, would it make sense to have a calendar view (similar to the one on desktop) for mobile, where you could see all the bookings in a timeline?

**Comment by hrvojeerjavec** [comment]
Yes, you are correct, I refer to the booking list in mobile app:

![WhatsApp Image 2023-04-28 at 18 03 53](https://user-images.githubusercontent.com/6393629/235197992-156f102e-a735-497e-b64c-175625fe1621.jpeg)

Calendar would be especially useful in this preseason, because it would easily let you know when each boat is having its first charter, and it would help with the overview and tasks prioritization

**Comment by yergom** [comment]
I've implemented a simple/complex selector (similar to the one in the maintenance task page), so you can easily switch between both views.

**Comment by cindyallis** [comment]
@hrvojeerjavec let us know what you think of the new compressed view (enabled by the switch at the top left corner). Is it sufficient to have just the boat name and status there or would you need any other info?

**Comment by hrvojeerjavec** [comment]
I think the status icons are more useful than the overal status like (pending, ready for checkin etc.) If you can fit the icons, and communicate the status with some color I think it would be better.

**Comment by cindyallis** [comment]
@yergom maybe we can remove the dates + status tag and show the boat name + icons below or right of the boat name it in the compressed version?
