### ISSUE TITLE
Delay when button is pressed

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#12]
When a user presses the button to mark something is done (example boat is cleaned inside), the delay is couple of seconds before it changes. This makes people think they need to press again, and then they unmark it by accident.

This seems like app is waiting for server response, which is ok, but lacks feedback to the user that the app recognized he pressed the button. It would be more intuitive if it changed the color when in progress.

**Comment by yergom** [comment]
I've implemented optimistic updates for booking states. This means that even with big network latency, users will get direct feedback on pressing the booking's buttons.

**Comment by hrvojeerjavec** [comment]
What happens if the update of the booking status fails? (For example internet problem)

**Comment by cindyallis** [comment]
Then the booking status button shows as unchecked again
