### ISSUE TITLE
Handling of traditional checkins through floatist

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#13]
We have cases when the client is not willing to use floatist but the traditional paper way. Since he does not do the precheck or check in floatist, his charter status in floatist is left as "ready to sail". Our skippers had different approach to this, some left it like that, while some made a fake checkin where everything is marked ok.

I suggest we have an option to take a picture of the checkin list add it to floatist and have a way to know from the bookings list view that this boat has the traditional checkin (Maybe different color of the check-in icon?). Status should communicate the boat is "Ready to sail".

**Comment by cindyallis** [comment]
Hi @hrvojeerjavec interesting point. In theory we could add a button next to the check-in icon in the mobile with a text like `Paper check-in`, but the risk of offering such a button is that your team will be tempted more often to fall back to that old way of doing things. If it is okay with you, I suggest we wait with this for a while an reevaluate the need for such a button in a few weeks / months

**Comment by hrvojeerjavec** [comment]
I think you don't have to worry about paper. We will always have couple of people that will prefer paper. This button should be available only to our workers, and weather it is paper or digital it is determined on reception checkin. Also, some people have problems with the app and need to use paper. Having a paper checkin available will give our workers the best experience, and ability to rely on Floatist. It is more than a check-in tool for our wokrers, and the only thing that repels them is when it is not working properly, like gives confusing/unerliable information. This is exactly why distinguishing the paper/digital approach is needed.

**Comment by cindyallis** [comment]
Hi @hrvojeerjavec, okay clear, we can implement a button to mark the check-in as completed offline. @yergom FYI

**Comment by hrvojeerjavec** [comment]
Can you please add a possibility to attach a picture, also we need this really urgent.

**Comment by yergom** [comment]
The way I've decided to implement it is as follows:
It's possible to submit a paper check-in:
![image](https://github.com/Floatist/Floatist-support/assets/1982805/2d777c4c-5f27-4a56-b767-caae9a66c80d)

which opens:
![image](https://github.com/Floatist/Floatist-support/assets/1982805/5d75e0c7-dc79-4cbe-afac-21be97f46ccc)

From there you can take picture directly using the camera, or add pictures from the device

![image](https://github.com/Floatist/Floatist-support/assets/1982805/45265b5b-f53c-4584-b830-81bbef0e88e6)
It's possible to crop the image manually, or flip it:
![image](https://github.com/Floatist/Floatist-support/assets/1982805/21f3bb6f-2d7d-41b6-a22d-e06a592c7f71)

Once done, we submit.

Some questions for @hrvojeerjavec:
- Can you envision the need of having both paper submission and digital submission?
- What about having a check-in in paper, but a check-out digital? Is this what you would do in reality?

**Comment by cindyallis** [comment]
@yergom I just discussed this with Hrovje:
- No need to have both paper submission and digital submission in one check-in / check-out. It will be either or.
- If check-in is in paper, check-out will also have to be on paper, and vice versa.
