### ISSUE TITLE
Logging the statuses

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#15]
We need to see who and when marked each of the status flags for a specific booking.
This is great to see when was the boat ready for checkin, and when he actually finished the check.

**Comment by yergom** [comment]
I would like to understand a bit better this request, as I see two possible ways of implementing it:
- Option 1: We store, per state (boolean) who last modified it, and when
- Option 2: We implement audit trailing for the booking state. Every time the state changes, we log the state transition, the user, and the timestamp. 

The second option is much more powerful, as that would allow us to have a booking history, of who changed what. That would also work when a state is transitioned multiple times. Is this what you want? 
Another question related to this. Is it enough to have this history for a specific booking, or would it be useful to have a historical view across bookings? Going even further, should this view across bookings be part of the boat log as well, and in that case, why would that be useful?

**Comment by hrvojeerjavec** [comment]
Number 2 would be what we need. We had a case where we needed it as a history of a specific booking. I think there is no use of it as part of a boat log. Historical view across bookings would be some kind of newsfeed which could be very useful if it wouldn't end up as a swarm of information. I am not sure how it would end up in practice.

**Comment by hrvojeerjavec** [comment]
Just to clarify, logs are extremely important and we need them as soon as possible. Also, the more I think about it, the more newsfeed makes sense. It would be a view to see what is going on in the base, and how are things progressing. 

Please make it happen.

**Comment by cindyallis** [comment]
Hi @hrvojeerjavec, noted. Im currently working on designs for this feature and Albert and I will discuss those early next week. We will keep you posted

**Comment by cindyallis** [comment]
Hi @hrvojeerjavec one question: how long would you want this information to be stored?

**Comment by hrvojeerjavec** [comment]
As long as possible. We can get a complaint from the client long time after his charter finished, and might need the data to reconstruct what has happened. Also it is good to see how our workers are progressing with their performance, which could be useful even through years. 

Does it take a lot of space?

**Comment by yergom** [comment]
Hi @hrvojeerjavec, I've just released the first version. We are calling it Booking Activity stream. For now, we keep track of all the changes in state, and you can see when, what and who did something for a booking. 
![image](https://github.com/Floatist/Floatist-support/assets/1982805/89166db5-e828-4bb9-bc4f-a99209a277b2)
The views is updated in soft real time, and uses an infinite scroll so you can look at the past.

In future versions we will add filtering (my boat, my bases, all), but also filters by user, by booking and by boat. We will also add a UI specific for booking, and implement mobile UIs as well. All of this will happen the coming days/weeks, but you can give it a try today and tell us what you think.

**Comment by yergom** [comment]
@hrvojeerjavec I've added the same view to mobile, it can be accessed through the bookings panel, on the top right corner. The list is virtualized, so performance will be very good even if we load 1000s of events. Clicking on an element will bring you to the specific booking page.
Next steps are implementing filtering, adding a UI per booking, and some nice goodies like visual indications showing new events when the view is updated. Stay tuned.
![image](https://github.com/Floatist/Floatist-support/assets/1982805/baca13e0-7e2b-45d7-af12-fa8774d62aca)

At the same time, we are also starting to implement better UX patterns, like for example making the header disappear so that you can see more events when scrolling down. We will apply these patterns consistently throughout the app in the next days.
