### ISSUE TITLE
Check-in filter

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#17]
We have a boat that has a booking since Saturday, but the guest was coming yesterday. When using the checkin filter, it doesn't show this booking even though the boat is still in the the "Ready for checkin" status.

**Comment by cindyallis** [comment]
hey @hrvojeerjavec, this is to be expected, as currently our Check-in and check-out filter is based on the actual starting dates of a booking. To give you more details of how it works:
- `Check-in` filter: will show you all bookings with start date `Today`, `Tomorrow`, `Yesterday`. This means that if a guest is coming late (on Sunday) it will still work. However we did not include the case where a guest would only show up on Tuesday. Would you say this happens more often, and we should include start date + 2 (Monday) and start date + 3 (Tuesday) as well in the check-in filter?
- `Check-out` filter: will show you all bookings with end date `yesterday`, `today`, `tomorrow`, or the `day after tomorrow`. Which means you can see it on Wednesday, Thursday, Friday, Saturday (assuming a standard Sat-Sat booking of course)

Let us know what you think we should do with it :)

**Comment by hrvojeerjavec** [comment]
Well I was thinking if you could make use of the status of the booking, it was "Ready for checkin". 
Then again, when I rethink it,  I can't see how it is used without some unwanted side-effects. For example showing all checkins from Today, Tomorrow, Yesterday OR earlier if status is still "ready for checkin". 

Side-effects I can think of right away are:

- Because of the filter, the booking will disappear from the list as soon as it is marked as "Ready to sail", which wasn't the usual scenario
- There might be cases of bookings never having a checkin (guest doesn't arrive), so the booking could stay in checkin phase forever and show up when not needed. This should be handled by manually declaring the booking finished.
- if the boat is not "Ready for checkin" but "Pending", it would not show up.

All in all, this is getting complicated, and there aren't many cases like this. I think we can work well with what we have, so the worker can use other filters for this. Search by boat with a large date span would be the best approach.

Maybe if you think of something better, or if this will show to be a bigger problem in the future, there would be a need to review this problem.

**Comment by yergom** [comment]
I had a similar concern, @hrvojeerjavec . We will always find multiple edge cases, but solving them might have, as you've stated, even more corner cases. I'm closing the issue, and if this becomes a problem, let's review the options of what can we do.
