### ISSUE TITLE
Actions over multiple tasks

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#2]
It would be great if I could put due date on multiple tasks, not just assign tasks. I have a use case where I have a boat that needs to get ready for first booking, and would like to set that due date on all its tasks.

This is not really an issue, more of a wishlist. Maybe we could have a label in github for such?

![image](https://user-images.githubusercontent.com/6393629/228377044-34d60a34-e92e-4df1-bd5b-f83bd2d2b6d7.png)

**Comment by Lok3rs** [comment]
@hrvojeerjavec  

Hello ;-)

We've been able to add such an option, it's already available in app.
