### ISSUE TITLE
Merging/splitting bookings

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#4]
We have a situation where a regata is booked on 1.4., but some clients decided to book couple of days before it. In mmk it is represented as two separate bookings: one from 30.3. till 1.4. and second is 1.4. till 8.4. Effectively in Floatist we should make just one check-in on 30.3. which would span till 8.4.

There were some cases last year where one 4 week booking had a check-in/out every week with new crew.

In this terms we need to be able to handle it, first thing on my mind is manual adjustment (split/merge) in Floatist.

**Comment by cindyallis** [comment]
Hi Hrvoje, we have read your issue and are thinking whether or not this is something we can tackle in the short term, as it is quite a complex one. thanks!

**Comment by cindyallis** [comment]
@yergom I discussed this with Hrvoje and there is already a good enough solution: they can manually create a booking in floatist that either spans the two MMK bookings that should be merged or create two separate bookings that should be split. So closing this issue.
