### ISSUE TITLE
Boat name as default search criteria

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#6]
Currently default search option on the mobile app is client name, although in practice it is rarely used. Much more often the client tells the name of the boat because it is more convenient than to spell out his name and surname. In my experience, boat name would be the most used search criteria.

**Comment by yergom** [comment]
This is interesting, so it might make sense to move the client name into the filter panel, and have a boat selector as the main input in the global page?

**Comment by hrvojeerjavec** [comment]
Yes, exactly.

**Comment by yergom** [comment]
@cindyallis I've been thinking about this, but I'm not convinced about the UX aspect of it. We are using a multiselect component for boats, and this one grows with the amount of boats selected. This works great when the component is within a form. However, using it as the main filter panel would cause things like the following:
![image](https://user-images.githubusercontent.com/1982805/235841210-a741af06-de66-4061-933b-7eeb95d43f41.png)
Which does not make sense. Making sure that the height cannot grow would be an option...but then as soon as more than 2 boats are selected, you quickly loose the overview of what boats are selected.

**Comment by yergom** [comment]
In the end I've opted to implement a local search:
![image](https://user-images.githubusercontent.com/1982805/235919844-97596f0a-6ea2-4258-a7c2-f67f7a5c9256.png)

For a given data view, you can now filter on boat or client name. I think this covers your use case, as normally your operators will have selected `My boats` + `Check-in` filters, so they can quickly filter on that view to get a specific boat's booking.

**Comment by hrvojeerjavec** [comment]
I like the criteria how it searches the list now, but it is freezing up. It becomes unresponsive when I am entering letters.

**Comment by yergom** [comment]
I see, i debounced the input....but maybe i should have applied a longer timeout value. I will fix it tomorrow morning asap.

**Comment by yergom** [comment]
@hrvojeerjavec This is fixed in today's release. The problem was that eventhough the value was debounced, we were triggering re-renders per key stroke. This is now fixed, and the component only re-renders 1 time once the user stops typing.
