### ISSUE TITLE
Autofilling client name and surname on checkin

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#7]
I am not sure about legal matters here, but wouldn't it be convenient to have autofill of the clients name if we already have that information in the app?

**Comment by cindyallis** [comment]
Hi hrvoje, yes we can actually prefill but we will keep the field editable in case the lead booker name is not the person doing the check-in. @Lok3rs can you pick this one up please?

**Comment by hrvojeerjavec** [comment]
Yes that seems correct to me.
