### ISSUE TITLE
Names for appliaction users

### ISSUE THREAD

**Issue by hrvojeerjavec** [Floatist/Floatist-support#8]
We need Names and Surnames to be assigned to our users because emails are not clear enough.

**Comment by cindyallis** [comment]
Hi Hrvoje, we are working on this one, we will try to finish it before coming Saturday, I will let you know once done!

**Comment by yergom** [comment]
We've created a User profile section. Note that the first name and last name is a property of the user itself, and cannot be changed by administrators. Every user can manage its own profile from both the desktop and mobile versions. If the first name/last name are not specified, we still fallback to the email.
![image](https://user-images.githubusercontent.com/1982805/235654784-e44dc50e-3e1f-4467-ad52-2dbdd06944ba.png)
![image](https://user-images.githubusercontent.com/1982805/235654865-5458f192-f3a8-4400-a4b1-9d4dbc0ff8d7.png)
